### ISSUE TITLE
BetterSADX-bits tracker summary AKA 4.1 to-do list

### ISSUE THREAD

**Issue by cheatfreak47** [Carlmundo/BetterSADX#1]
For Carlmundo:

- [x] Update the SADX Mod Loader to the latest version
- [x] You must actually delete **everything** from `/Install_Mods_DC/mods/DC_Mods` and `/Install_Mods_Common/mods/DC_Mods` and place everything from [this download](https://drive.google.com/open?id=0Bylw5DY5vYGWeUxzRkJXdXZvaXc) in the former location, except for HD_DCStyle which goes in the latter directory.
- [x] Update [SADX-DC-Lighting](https://github.com/SonicFreak94/sadx-dc-lighting/releases/download/v1.2/sadx-dc-lighting.7z).
- [x] Update SADX Fixed Edition.
- [x] Move sadx-frame-limit from `Install_Shared\mods\` to `Install_Speedrun/mods` as it seems to not be that useful for anyone but speedrunners, and to varying degrees for them- as such it will be included but disabled by default.
- [x] Include [HDDC_Unscale](https://github.com/cheatfreak47/BetterSADX-bits/releases/download/4.1/HDDC_Unscale.7z) in `Install_Mods_Common\mods\` - a mod to unscale load screen images in HDDC_Style so the game is friendly to sub-HD resolutions, once the mod-loader is updated to handle this on it's own, this will be removed from BetterSADX.
- [x] Remove DC_CharTextures and replace with the new one, [Mimic DC Textures](https://github.com/cheatfreak47/BetterSADX-bits/releases/download/4.1/MimicDCTextures.7z). - A mod that maps the Dreamcast style textures to the DX models, in the future this will be included only as a bonus because ItsEasyActually is porting the Dreamcast Models, which I plan on including for Dreamcast Conversion installs.
- [x] Remove code to make a copy of `RE-US.mpg` because the file `RE-JP.mpg` was apparently never used anyway, I had MainMemory check- however we should keep it in the assets for the steam conversion because a mod could take advantage of it. (In case MM or SF94 want to make a language-fix mod sometime).
- [x] Changes to text in the installer: all user seen references to `Dreamcast Edition` should be changed to `Dreamcast Conversion`;  `Speedrunner` should be changed to `Minimal/Speedruns`; and `Speedrun Install` should be changed to `Minimal/Speedrun Install`.
- [x] Make a new build of course. 👍 
- [x] We both need to discuss and figure out how to handle users that need to update.
- [x] ~~Remove `ECGardenOceanFix` and `MR_FinalEggFix` as those are rolled into the new SADX:FE if I'm not mistaken.~ I was mistaken
- [x] Manually update the 4 older BetterSADX-bits mods just in case mod-updater is tripped up by them being possibly outdated.
- [x] Remove DC_EnvMaps from DC_Mods
- [x] Manually Update BetterSADX_version again, because the one included was outdated, current version should be 4.1 in the mod.ini
- [x] move d3d8.dll to `Install_Mods_DC` instead of `Install_Mods_Common` since it is not required for BetterSADX Standard, and only serves to potentially cause performance issues otherwise.
- [x] Move BetterSADX group page to "Install Finished" as a checkbox.
- [x] Your INI tweak that fixes monitor selection and removes unconfigured window size
- [x] Update to DC ini that unchecks DC_TornadoModels because I accidentally left it checked. My bad. Here. [DC Config.zip](https://github.com/Carlmundo/BetterSADX/files/1027652/DC.Config.zip)

---
For CheatFreak:
- [x] Make new INIs for each build, remember to change everything appropriately for the new changes.
- [x] Send betas out to testers before release.
- [x] Play through the game once to verify everything is working before we push it.
- [x] Update guide (if needed)

**Comment by cheatfreak47** [comment]
After we have a working build of 4.1- we need to consider how we're having people update before we release 4.1 publically.

We can't just say "lol backup your save, reinstall" every time- that's kind of inconvenient for our existing users. 😕 

The way I see it, we have 3 options:

* We could make it so the main patch is capable of updating users, by detecting if they are running 4.0 and wiping out all the files that the current version has updated. This is probably the most ideal, but it's also kind of a pain.

* We could make a new hotpatch and do it in a much smarter way so it's less of a pain in the ass. 

* Here's another idea I had, we could make a sort of BetterSADX Uninstaller, to aid and minimize the amount of work it requires to have users update- The idea is that it will wipe out all the known BetterSADX files, leaving only the known steam version files in the correct places, user savedata, and, basically undoing as much of what BetterSADX does as possible, and instructing the user on verifying the integrity of the game cache. This is not really ideal but I guess it would work.
