### ISSUE TITLE
4.1.2 checklist

### ISSUE THREAD

**Issue by cheatfreak47** [Carlmundo/BetterSADX#8]
- [x] Update Mod Manager and Loader and make sure the dll updates as well
- [x] Update all mods to latest builds, remove junk caused by updating, and verify all mods.
- [x] Update d3d wrapper manually: https://github.com/crosire/d3d8to9/releases/tag/v1.4.0
- [x] Include https://github.com/ItsEasyActually/SA1_Chars/releases
- [x] Make sure to delete the unneeded dir in dc branch: /mods/DC_Mods/OptionalMods/DC_TornadoModels/

SA1 Chars will not be enabled by default- but will be there for those that are interested ✌️
for now at least.

**Comment by cheatfreak47** [comment]
new dreamcast ini: https://u.teknik.io/fB1G9.7z

**Comment by cheatfreak47** [comment]
[SADXModLoader.zip](https://github.com/Carlmundo/BetterSADX/files/1226441/SADXModLoader.zip)
there my bad

**Comment by cheatfreak47** [comment]
[SADXModLoader.zip](https://github.com/Carlmundo/BetterSADX/files/1226447/SADXModLoader.zip)
no chao garden mod
